default:
	gcc -o src src.c
	gcc -o swap_pair swap_pair.c
	gcc -o reverse reverse.c
	gcc -o rev_recursive rev_recursive.c
	gcc -o Fisher_Yates_shuffle Fisher_Yates_shuffle.c

clean:
	rm src
	rm swap_pair
	rm reverse
	rm rev_recursive
	rm Fisher_Yates_shuffle
